"""
hdl_generator.py – Transpile CircuitJSON to synthesisable Verilog HDL.
"""

from __future__ import annotations

import re
from collections import defaultdict
from typing import Any

from vilm2ccg.circuit_json import CircuitJSON, CircuitEdge, CircuitNode


# ---------------------------------------------------------------------------
# Gate-level Verilog expression builders
# ---------------------------------------------------------------------------

_GATE_OPERATORS: dict[str, str] = {
    "and": "&",
    "or": "|",
    "xor": "^",
    "nand": "&",
    "nor": "|",
    "xnor": "^",
}

_GATE_NEGATE: set[str] = {"not", "nand", "nor", "xnor"}


def _signal_name(edge: CircuitEdge, node: CircuitNode) -> str:
    """Return a Verilog-safe net name for an edge arriving at *node*."""
    return edge.name if edge.name else f"w_{edge.from_node}_to_{node.id}"


# ---------------------------------------------------------------------------
# Verilog module generator
# ---------------------------------------------------------------------------


class VerilogGenerator:
    """Convert a :class:`~vilm2ccg.circuit_json.CircuitJSON` to Verilog."""

    def __init__(self, circuit: CircuitJSON) -> None:
        self.circuit = circuit
        # Map: node_id → list of incoming CircuitEdge objects
        self._incoming: dict[str, list[CircuitEdge]] = defaultdict(list)
        # Map: node_id → net name produced by that node (output wire)
        self._node_net: dict[str, str] = {}

        for edge in circuit.edges:
            self._incoming[edge.to_node].append(edge)

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def generate(self) -> str:
        """Return the complete Verilog module as a string."""
        lines: list[str] = []

        inputs = self.circuit.get_inputs()
        outputs = self.circuit.get_outputs()
        gates = self.circuit.get_gates()

        module_name = _safe_id(self.circuit.circuit_name)
        port_names = (
            [_safe_id(n.name) for n in inputs]
            + [_safe_id(n.name) for n in outputs]
        )

        # Module header
        lines.append(f"// Auto-generated by ViLM2CCG")
        lines.append(f"// Circuit: {self.circuit.circuit_name}")
        lines.append(f"// Description: {self.circuit.description}")
        lines.append("")
        lines.append(f"module {module_name} (")
        lines.append("    " + ",\n    ".join(port_names))
        lines.append(");")
        lines.append("")

        # Port declarations
        for node in inputs:
            w = node.width
            if w > 1:
                lines.append(f"    input  [{w - 1}:0] {_safe_id(node.name)};")
            else:
                lines.append(f"    input  {_safe_id(node.name)};")

        for node in outputs:
            w = node.width
            if w > 1:
                lines.append(f"    output [{w - 1}:0] {_safe_id(node.name)};")
            else:
                lines.append(f"    output {_safe_id(node.name)};")

        lines.append("")

        # Assign input node nets to their port names
        for node in inputs:
            self._node_net[node.id] = _safe_id(node.name)

        # Internal wire declarations
        internal_wires: list[str] = []
        for node in gates:
            wire_name = f"w_{_safe_id(node.id)}"
            self._node_net[node.id] = wire_name
            internal_wires.append(f"    wire {wire_name};")

        if internal_wires:
            lines.extend(internal_wires)
            lines.append("")

        # Gate assignments
        for node in gates:
            stmt = self._gate_assignment(node)
            if stmt:
                lines.append(f"    {stmt}")

        lines.append("")

        # Output assignments
        for node in outputs:
            incoming = self._incoming.get(node.id, [])
            if incoming:
                src_net = self._node_net.get(incoming[0].from_node, "1'bx")
                lines.append(f"    assign {_safe_id(node.name)} = {src_net};")

        lines.append("")
        lines.append("endmodule")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Per-gate logic
    # ------------------------------------------------------------------

    def _gate_assignment(self, node: CircuitNode) -> str:
        ntype = node.type.lower()
        out_net = self._node_net.get(node.id, f"w_{node.id}")

        incoming = sorted(self._incoming.get(node.id, []), key=lambda e: e.to_port)
        in_nets = [self._node_net.get(e.from_node, "1'bx") for e in incoming]

        if ntype in {"buf"}:
            src = in_nets[0] if in_nets else "1'bx"
            return f"assign {out_net} = {src};"

        if ntype == "not":
            src = in_nets[0] if in_nets else "1'bx"
            return f"assign {out_net} = ~{src};"

        if ntype == "mux":
            return self._mux_assignment(node, out_net, incoming)

        if ntype in _GATE_OPERATORS:
            op = _GATE_OPERATORS[ntype]
            expr = f" {op} ".join(in_nets) if in_nets else "1'bx"
            if ntype in _GATE_NEGATE:
                expr = f"~({expr})"
            return f"assign {out_net} = {expr};"

        # Unknown gate type – use a placeholder
        return f"// WARNING: unsupported gate type '{ntype}'"

    def _mux_assignment(
        self,
        node: CircuitNode,
        out_net: str,
        incoming: list[CircuitEdge],
    ) -> str:
        n_data: int = node.metadata.get("n_data", 2)
        n_sel: int = node.metadata.get("n_sel", 1)

        # Partition edges into data and select
        sorted_incoming = sorted(incoming, key=lambda e: e.to_port)
        data_nets = [self._node_net.get(e.from_node, "1'bx") for e in sorted_incoming[:n_data]]
        sel_nets = [self._node_net.get(e.from_node, "1'bx") for e in sorted_incoming[n_data:]]

        if n_sel == 1 and len(sel_nets) >= 1:
            s = sel_nets[0]
            d1 = data_nets[1] if len(data_nets) > 1 else "1'bx"
            d0 = data_nets[0] if len(data_nets) > 0 else "1'bx"
            return f"assign {out_net} = {s} ? {d1} : {d0};"

        # Multi-select: build a chain of ternary expressions
        if not sel_nets:
            return f"assign {out_net} = 1'bx;"

        sel_concat = "{" + ", ".join(reversed(sel_nets)) + "}"
        expr_parts: list[str] = []
        for idx, dnet in enumerate(data_nets):
            bin_str = format(idx, f"0{n_sel}b")
            expr_parts.append(f"({sel_concat} == {n_sel}'b{bin_str}) ? {dnet}")

        last = data_nets[-1] if data_nets else "1'bx"
        expr = " : ".join(expr_parts) + f" : {last}"
        return f"assign {out_net} = {expr};"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _safe_id(name: str) -> str:
    """Convert a name to a Verilog-safe identifier."""
    safe = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if safe and safe[0].isdigit():
        safe = "_" + safe
    return safe


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_verilog(circuit: CircuitJSON) -> str:
    """Generate synthesisable Verilog from a :class:`~vilm2ccg.circuit_json.CircuitJSON`.

    Returns the Verilog source code as a string.
    """
    gen = VerilogGenerator(circuit)
    return gen.generate()
